### ISSUE TITLE
Server crashes on start in minecraft 1.12.2

### ISSUE THREAD

**Issue by Eruzaaa** [Rift-Modding-Group/Prehistoric-Rift-Mod#79]
The server crashes when starting on minecraft 1.12.2 I have a crash report attached. The crash happens even with no other mods installed. 
https://pastebin.com/hNm7WP2J

**Comment by ANightDazingZoroark** [comment]
should (hopefully) be fixed by this update

**Comment by Eruzaaa** [comment]
Thank you for spending time working on it, I appreciate it. If it works my friends will really enjoy it, you've made a really good mod.

**Comment by ANightDazingZoroark** [comment]
ur welc, am currently writing the patch notes while we speak

**Comment by Eruzaaa** [comment]
I got a server to boot and it seems to be working fine so far, Thanks!
